# Generated by Django 3.1.7 on 2021-04-11 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0002_auto_20210411_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifytoken',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
